### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ilucker** [infinityworksltd/ranch-eye#2]
It seems like rancher is not using cAdviser since [v1.2](https://github.com/rancher/rancher/releases/tag/v1.2.0) 

As such this repository is not needed. Could you please update documentation.

**Comment by Rucknar** [comment]
Indeed, the guide and catalog entry have been updated to reflect the change, ranch-eye its-self though hasn't. I'll update the docs to make it clear.

**Comment by Rucknar** [comment]
Updated.

**Comment by ilucker** [comment]
Thank you
